// "use client"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { RegisterLink, LoginLink } from "@kinde-oss/kinde-auth-nextjs/components";
import '../app/styles/global.css';
import React from 'react';
import Link from "next/link";
// import Image from "next/image";


export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      {/* <section> */}
        <nav>
          <div className="navbar">
            <Link href="/"> 
                    <img className="icon-tag" src="/icon.jpg" alt="fghj"/>
            </Link>
            <ul>
              <li>
              <Link href="/">
                  home
                </Link>
              </li>
              <li>
              <Link href="/">
                Traffic <br/> rules
                </Link>
              </li>
              <li>
                <RegisterLink>Sign up</RegisterLink>
              </li>
              <li>
                <LoginLink>Sign in</LoginLink>
              </li>
              <li>
              <Link href="/">
                About <br/> us
                </Link>
              </li>
            </ul>
          </div>
        </nav>

      {/* </section> */}
        {children}
        </body>
    </html>
  )
}
